name: Manage Patches
on:
  release:
    types: released
jobs:
  delete_patches_on_release:
    runs-on: ubuntu-latest
    # currently only releases in main branch are considered
#    if: github.event.release.target_commitish == 'main'
    if: github.event.release.target_commitish == 'test/github_test'
    steps:
      - uses: actions/checkout@v2
        with:
          # By default, tag is checked out. It needs to check out branch to commit to.
#          ref: 'main'
          ref: 'test/github_test'
      - run: |
         find kubemarine/patches/ -not -path "kubemarine/patches/__init__.py" -not -path "kubemarine/patches/" -delete
         cp kubemarine/resources/etalons/patches/__init__.py kubemarine/patches/__init__.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Delete all patches after release
